### ISSUE TITLE
FIND-HPEOA fails to detect Onboard Administrator

### ISSUE THREAD

**Issue by mreid2005** [HewlettPackard/PowerShell-ProLiant-SDK#11]
Compare results of the two commands - find-hpeoa does not detect OA. find-hpoa does.

**OA Cmdlet - Version:2.0.0.0 (6 Aug 2018)**
PS E:\SCRIPTS\VALIDATIONS\validate_subnets> **find-hpeoa** 172.11.111.111
WARNING: It might take a while to search for all the HP OAs if the input is a very large range. Use Verbose for more information.

**hpOA module Version                 : 1.1.0.3**
PS E:\SCRIPTS\VALIDATIONS\validate_subnets> **find-hpoa** 172.29.111.111
Warning : It might take a while to search for all the HP OAs if the input is a very large range. Use Verbose for more information.

IP           : 172.29.111.111
Hostname     : <customer data obscured>
ProductName  : BladeSystem c7000 DDR2 Onboard Administrator with KVM
Firmware     : 4.85
Role         : ACTIVE
SerialNumber : OB35CP1492    
UUID         : 09OB35CP1492

**Comment by hp-powershell** [comment]
Hi,

Currently we do not have any scheduled releases for OA cmdlets . 

Thanks & Regards,
Powershell Team
