### ISSUE TITLE
connect-hperedfish doesn't accept pipeline from find-hperedfish

### ISSUE THREAD

**Issue by mreid2005** [HewlettPackard/PowerShell-ProLiant-SDK#12]
Connect-hperedfish will not accept pipeline input from find-hperedfish.

pretty straightforward, should be able to pipe the results from find-hperedfish to connect-hperedfish
similar to the find-hpilo cmdlet.

**Comment by hp-powershell** [comment]
Hi,

Redfish Cmdlets don't support multithreading or range of IP as it's input like iLO cmdlets. It takes only single IP address at a time and gives the result for that address. So piping the output data obtained from Find to Connect will connect to the last pingable IP obtained from Find-HPERedfih.

(Find-HPERedfish 10.168.10.1-20).IP | Connect-HPERedfish -Username admin -Password admin123

Thanks,
Hema
