### ISSUE TITLE
Documentation Update Request for HPEiLOCmdlets v2.2.0.0

### ISSUE THREAD

**Issue by mc1903** [HewlettPackard/PowerShell-ProLiant-SDK#15]
Hi,

I appreciate that the HPEiLOCmdlets v2.2.0.0 release is only a few days old, but the Release Notes and User Guide docs in the Hewlett Packard Enterprise Information Library (
http://h17007.www1.hpe.com/us/en/enterprise/servers/solutions/info-library/index.aspx?cat=scripting_tools_powershell#.XLJ0aOhKhaT) are linked to the old HPEiLOCmdlets v2.1.0.0 docs.

Also, please can you include a quick lookup table in one of the documents that shows which iLO version (& minimum firmware version) is supported by each Cmdlet?

Thanks
Martin

**Comment by hp-powershell** [comment]
Hi Martin,

Can you check again now all 2.2 docs are available in the above link. Maybe you might have checked before the go live status of the docs. 

Regarding the iLO firmware version update for each cmdlets i don't think we follow that method. But whenever we release new iLO cmdlets you can check in the guide which version we qualified in the UG\RN document itself against all cmdlets. Individually we don't provide those details.

Thanks,
Gokul
