### ISSUE TITLE
Feature Request: HPEiLOCmdlets. Provide the iLO Temperature & Power usage graphs as Base64 encoded images

### ISSUE THREAD

**Issue by mc1903** [HewlettPackard/PowerShell-ProLiant-SDK#16]
Hello,

I would like to make a feature request for the HPEiLOCmdlets PowerShell module.

Please can you make the graphs for both temperature (2D & 3D, front & rear views) and power usage (20 minute & 24 hour), that are already provided via the Web GUI, available as Base64 encoded images/strings?

Many Thanks
Martin

![HPE iLO4 - Temperature Graphic](https://user-images.githubusercontent.com/13692287/56325589-a7229580-616a-11e9-83b0-53e272ba68cb.PNG)

![HPE iLO4 - Power Meter Graphics](https://user-images.githubusercontent.com/13692287/56325595-aab61c80-616a-11e9-8081-dba6fd5e88f2.PNG)

**Comment by hp-powershell** [comment]
Hi,

Can i know the reason for asking for this feature request. Not many customers are interested in automation of graphs from iLO. I want to hear the strong reason behind this requirement.

Thanks,
Gokul

**Comment by mc1903** [comment]
Hi Gokul,

I simply would like to use these graphs as graphics in a report that I am creating in PowerShell using the existing HPEiLOCmdlets (API) module. They give a clear visual snapshot of the server temperature & power status; I guess that is why you put them in the GUI in the first place?

You give the X,Y coordinates for the temperature sensors via the API, so I could probably create my own temperature graph. However, you do not provide the power data via the API to allow me to create my own power graphs and it would be nice to have the same look and feel as the GUI. 

Additionally, you are generating these images already for the GUI, how complex would it be to convert them into a Base64 string?

I cannot speak to your research into customers who do not want to use automation of graphs from iLO, but this is something I would use. Many vendors are now ensuring that there is at feature parity between their API and their GUI.

Thanks
Martin

**Comment by hp-powershell** [comment]
Hi Martin,

I had a discussion with iLO expert and below is the answer from him.

Regarding X & Y coordinates for power data they are not provided by iLO server but how it works is you need to record the time on X-axis and power data information (got at that time) against Y-axis to get the power graphs similar to iLO Web GUI. Say you need to get the power data at a frequency interval of every 5 minutes (change to suitable interval) and you start plotting the graph using this data as mentioned above.

As you mentioned in your earlier response you already get temperature sensors X and Y coordinates data and with that you can plot a 2-D graph. Use different color coding for different level of temperatures. Like RED for higher temperature and GREEN for lowest temperature recordings.

As per above data iLO is infact providing all necessary data for that point in time.  So its the consumer who needs to use this data and plot the graph the way he desires.

Hope this helped you in solving the issue.

Thanks,
Gokul

**Comment by mc1903** [comment]
Gokul,

Your/his reply is unhelpful and condescending.

Why would I sample & store point-in-time power usage data every 5 minutes over a 24 hour period, when that data is already available/stored within the iLO? (24-Hour History Graph)

If you returned the last 24 hours of 5 minute power usage data via a single execution of the API/HPEiLOCmdlet, I would be able to recreate the graph myself!

Martin

**Comment by hp-powershell** [comment]
Martin,

Unfortunately iLO does not share this information via API's. So PowerShell interfaces will not be able to share the data.

Please talk to HPE Support team to raise your enhancement request for iLO Redfish team.

I am sorry i can't help you beyond at this moment.

Thanks,
Gokul
