### ISSUE TITLE
get-hpebiossetting

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#20]
Hi,
I'm searching for import/export XML/JSON server configuration for iLO/BIOS. I found only this command for export BIOS settings. But nothing for import BIOS and nothing for import/export repeated part of iLO. We use 6 different set of settings for location and lots of different server model. Do you have some solution or have you some plans for it?
Thanks
Ari

**Comment by hp-powershell** [comment]
Hi,

There is no cmdlet in BIOS for exporting the settings, but there are cmdlets in iLO5 (Gen10) for both importing and exporting iLO configuration.

The cmdlet Backup-HPEiLOSetting allows you to take a back up of the current settings which can be restored using the cmdlet Restore-HPEiLOSetting.

Regards,
Hema

**Comment by ariael** [comment]
Hi,
But this cmdlet is clearly only for some local backup. "This feature is not meant to duplicate a
configuration and apply it to a different iLO system." This is from your manual. Result is binary file specific for one server.
For deployment is needed import AND export ILO AND BIOS in XML or JSON - this is readable and editable format. Can be customized and repeatedly use for hundred of similar servers.
We need some method for automatic deploy servers and configuration files for ILO and BIOS is basic thing for this...

Thanks,
Regards
Ari
