### ISSUE TITLE
Problem with management open sessions

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#22]
Hi,
For management HPE server now we need 3 session open - iLO, BIOS and SA. Timeout can be set only in iLO. Others sessions will timeout and must be reopen - in real world new session is open, but old session still exist! Number of this sessions is very limited - 10. 
We don't have tools for management this sessions - evaluate numbers, automatically close old session (or refresh old session), set timeout for BIOS and SA, maybe use only one session (more complex object) for all three connection?
Thanks
Ari

**Comment by hp-powershell** [comment]
Hi,

We understood the problem, we are working on a common connector approach for all 3 modules. This is part of our roadmap but I cant guarantee in which release train it will go.

Thanks,
Hema

**Comment by ariael** [comment]
Hi,
I have some cmdlets for HPe servers, originally from another project for us.
Maybe you can use it.
For example one universal connect, active directory integration and similar.

Now I use mix of yours cmdlets and ours.
Ari.


Dne út 4. čvn 2019 7:35 uživatel Vijay Bhojwani <notifications@github.com>
napsal:
