### ISSUE TITLE
Set-HPEBIOSTPMConfiguration fails on Gen9 with TPM

### ISSUE THREAD

**Issue by tlauder** [HewlettPackard/PowerShell-ProLiant-SDK#24]
Hello - I'm trying to enable/clear/disable the TPM on a gen9 server with the Set-HPEBIOSTPMConfiguration command:
Set-HPEBIOSTPMConfiguration -Connection $con1 -TPM12Operation Enabled

The command returns an error:
"The parameter(s) listed in AffectedAttribute are not supported on the target server ProLiant DL360 Gen9. For more details about supported parameters, see the cmdlet help or the Troubleshooting chapter of BIOS Cmdlets user guide."

The TPM is installed and working:
Get-HPEBIOSTPMChipInfo -Connection $con1
IP       : x.x.x.x
Hostname : server.domain.com
Status   : OK
TPMType  : TPM12
TPMState : PresentAndDisabled

Any thoughts?

Thanks!
Todd

**Comment by hp-powershell** [comment]
Hi,

This is an issue in HPEBIOSCmdlets module. We will be fixing this in the next release.

Thanks,
Hema

**Comment by tlauder** [comment]
Do we have an ETA on the next release?
