### ISSUE TITLE
Get-HPEiLODirectoryGroup and iLO5

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#26]
Hi,
In manual is "The Get-HPEiLODirectoryGroup gets. This cmdlet is supported on iLO 4 and iLO5 servers."
In real:
$status = Get-HPEiLODirectoryGroup -Connection $script:connectionilo
$status.StatusInfo

             Category Message                        AffectedAttribute
             -------- -------                        -----------------
FeatureSupportability Feature not supported on iLO5. {}

**Comment by hp-powershell** [comment]
Hi,

The "Feature not supported on iLO5" comes  for one of the two reasons:
1.  The iLO Firmware version is less than 1.40. The directory cmdlets are suppported on iLO5 from iLO FW 1.40 onwards as the Redfish support for these features are available from 1.40 onwards.
2.  The HPEiLOCmdlets module version is not 2.2.0.0. These cmdlets  are supported on iLO5 from 2.2.0.0.

Could you please verify the iLO Firmware version and iLO cmdlets module version.

**Comment by ariael** [comment]
I'll version is 1.40 minimal, standard is 1.43

Dne út 11. čvn 2019 5:51 uživatel Vijay Bhojwani <notifications@github.com>
napsal:

**Comment by hp-powershell** [comment]
Hi, 

Can you please execute Get-HPEiLOModuleVersion and look for 'CurrentModuleVersion' property. The cmdlet is supported in 2.2.0.0. If the version is 2.2.0.0 and you are still facing the issue, could you please provide us the iLO details and the log file. 

To get the log file execute Enable-HPEiLOLog before executing the cmdlet Get-HPEiLODirectoryGroup.
