### ISSUE TITLE
The Get-HPEiLODirectoryGroup problem.  ILO1.40 and 1.43!

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#27]
Hi,
In manual is "The Get-HPEiLODirectoryGroup gets. This cmdlet is supported on iLO 4 and iLO5 servers."
In real:
$status = Get-HPEiLODirectoryGroup -Connection $script:connectionilo
$status.StatusInfo

         Category Message                        AffectedAttribute
         -------- -------                        -----------------
FeatureSupportability Feature not supported on iLO5. {}

**Comment by hp-powershell** [comment]
Hi,

Can you please execute Get-HPEiLOModuleVersion and look for 'CurrentModuleVersion' property. The cmdlet is supported in 2.2.0.0. If the version is 2.2.0.0 and you are still facing the issue, could you please provide us the iLO details and the log file.

To get the log file execute Enable-HPEiLOLog before executing the cmdlet Get-HPEiLODirectoryGroup

**Comment by ariael** [comment]
I try reinstall module (same version) and problem dismissed... Looks like some glitch...
