### ISSUE TITLE
Backup-HPEiLOSetting

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#28]
Hi,
I'm searching for import/export XML/JSON server configuration for iLO/BIOS (Gen10 is enough).
I found only this command for export/import BIOS settings in unreadable binary format.  We use  lots differents sets of configs by location and purpose and lots of different server model. 
Binary format is nice for some backup one precise server, but unusable in real world.
Do you have some "expand" function for this format? Or open readable version of save (XML/JSON)? 
Or maybe source file of this function, i can write this function, but i don't want start write totally incompatible code from scratch....

Thanks
Ari

**Comment by hp-powershell** [comment]
Hi,

The cmdlet Backup-HPEiLOSetting takes the backup of **iLO settings** and can be restored on that machine where the back up was taken using Restore-HPEiLOSetting. The settings cannot be viewed on the Powershell Console, it has to be applied to the iLO to view using the Restore cmdlet. XML/JSON format is not supported.

To get the current/pending settings of **BIOS** you can use the cmdlet Get-HPEBIOSSetting. 
The below execution gives us the current BIOS settings of that machine as PSObject. Similarly Pending settings, Current BIOS Boot settings etc. can be expanded and viewed.

PS C:/> $output = Get-HPEBIOSSetting  -Connection $connection
PS C:/> $output.CurrentBIOSSettings

**Comment by ariael** [comment]
Hi, 
Yes, this working, but still missing second part of this: Set-HPEBIOSSetting
Or i'm wrong? I found only lots of very targeted cmdlets, but for very large environment this is not good way. If i use this, scripts will be very complex  and need lots of effort. If i use few text config files, scripts will be straight and text file is easy for editing without changing powershell part.
I'm still searching for some workflow for usable multiply bios setting (and ideally iLO too).
Gen10 is enough, Gen9 is nice cream on top. We are have about more then 10000 servers and all solutions must be "clear" :)

**Comment by ariael** [comment]
Export all seetings from iLO and BIOS is possible via ilorest comand ServerClone...
It is possible implement same functionality into powershell? Export and Import JSON file with configurations?

**Comment by hp-powershell** [comment]
Hi,

We are looking into the feasibility of implementing this feature, we will provide you an update on the same.

Thanks,
Hema
