### ISSUE TITLE
Set-HPiLOPersistentBootOrder Inconsistency Remains

### ISSUE THREAD

**Issue by lzinga** [HewlettPackard/PowerShell-ProLiant-SDK#29]
Its fixed in 2.0.0.1 version.

_Originally posted by @hp-powershell in https://github.com/HewlettPackard/PowerShell-ProLiant-SDK/issues/3#issuecomment-421256454_

> 
> 
> Its fixed in 2.0.0.1 version.

I finally made the transition over but I am still encountering the same issues. I am working with version 2.2.0.0 of the cmdlets and I am still able to successfully have it change the boot order when running a command similar to the following - 
```PS
Set-HPEiLOPersistentBootOrder -Connection $connection -BootOrder "Boot000B"
Set-HPEiLOPersistentBootOrder -Connection $connection -BootOrder @("Boot000B", "Boot000D")
```
When using any of the following methods it fails saying invalid device choice.
```PS
Set-HPEiLOPersistentBootOrder -Connection $connection -BootOrder "Embedded LOM 1 Port 1 : HPE Ethernet 1Gb 4-port 331i Adapter - NIC (PXE IPv4)"
Set-HPEiLOPersistentBootOrder -Connection $connection -BootOrder "NETWORK1"
Set-HPEiLOPersistentBootOrder -Connection $connection -BootOrder @("NETWORK1","HDD","USB","CDROM","FLOPPY")
```

When using the Get-Help command, it says in the examples that the generic names should work -
```PS
Set-HPEiLOPersistentBootOrder -Connection $connection -BootOrder @("NETWORK1","HDD","USB","CDROM","FLOPPY")
```

So at this point I am still needing to parse through the raw data and find which boot code (Boot000B) is equal to the network interface.

**Comment by hp-powershell** [comment]
Hi,
 
The device are machine specific. Preferred way of setting the boot order would be to execute  Get-HPEiLOPersistentBootOrder to know the available device and set them according to your choice.

**Comment by lzinga** [comment]
Would that still need the boot code? Because using the name retrieved from `Get-HPEiLOPersistentBootOrder` like in the command below
```
Set-HPEiLOPersistentBootOrder -Connection $connection -BootOrder "Embedded LOM 1 Port 1 : HPE Ethernet 1Gb 4-port 331i Adapter - NIC (PXE IPv4)"
```
Also doesn't work, I would have to use `Boot000B` name and use that while running `Set-HPEiLOPersistentBootOrder` where the examples state that other more generic names can be used. Is this not the case?

**Comment by hp-powershell** [comment]
Hi,

Can you please share the machine details including model, Generation, firmware version as well as Get-HPEiLOPersistentBootOrder and Set-HPEiLOPersistentBootOrder output to further look into it.

Thanks
