### ISSUE TITLE
Problem with Get-HPERedfishIndex

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#30]
Hi,
I try "$index = Get-HPERedfishIndex -Session $session"
But result if full of errors. Target is iLO v 1.43 server ProLiant DL360 Gen10... All library is up-to-date.
Errors: "firmware is flashed" and lots of another is fully nonsense.

----------------------------------------------------------------
```powershell
$index = Get-HPERedfishIndex -Session $session
Step-ThroughNoteProperties : Schema not found for #Settings.v1_0_0.Settings
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 
Step-ThroughNoteProperties : 
iLO.2.8.ResourceTemporarilyUnavailable
Description: The resource is temporarily unavailable because the firmware is being flashed.
Message: The resource is temporarily unavailable because the firmware is being flashed.
NumberOfArgs: 0
ParamTypes: 
Resolution: Retry the operation when the firmware upgrade has completed.
Severity: Warning
-
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (500) Internal Server Error."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:1720 char:9
+         [System.Net.WebResponse] $resp = $httpWebRequest.GetResponse( ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 
Step-ThroughNoteProperties : 
iLO.2.8.InvalidOperationForSystemState
Description: The operation was not successful due to the current power state (for example, attempting to turn the power off when it is already off).
Message: The operation was not successful due to the current power state.
NumberOfArgs: 1
ParamTypes: string
Resolution: Verify that the system is in the correct power state, and then retry the operation.
Severity: Warning
-
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad Request."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:1720 char:9
+         [System.Net.WebResponse] $resp = $httpWebRequest.GetResponse( ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 
Step-ThroughNoteProperties : 
iLO.2.8.InvalidOperationForSystemState
Description: The operation was not successful due to the current power state (for example, attempting to turn the power off when it is already off).
Message: The operation was not successful due to the current power state.
NumberOfArgs: 1
ParamTypes: string
Resolution: Verify that the system is in the correct power state, and then retry the operation.
Severity: Warning
-
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad Request."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:1720 char:9
+         [System.Net.WebResponse] $resp = $httpWebRequest.GetResponse( ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 
Step-ThroughNoteProperties : 
iLO.2.8.InvalidOperationForSystemState
Description: The operation was not successful due to the current power state (for example, attempting to turn the power off when it is already off).
Message: The operation was not successful due to the current power state.
NumberOfArgs: 1
ParamTypes: string
Resolution: Verify that the system is in the correct power state, and then retry the operation.
Severity: Warning
-
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (400) Bad Request."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:1720 char:9
+         [System.Net.WebResponse] $resp = $httpWebRequest.GetResponse( ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 ```

**Comment by hp-powershell** [comment]
Hi,

Possible reasons for the above issue is as follows:
1. If not using advanced license key certain url's will not be accessible and it errors out.
2. It's looking for some schema which is not present.

The response object will still contain the data for all other available nodes inspite of the error.

Thanks,
Hema

**Comment by ariael** [comment]
Hi,
Thanks for reply.
I have advanced Ilo licence...
And i understand that sometimes schema don't exist.
But real problem is, that this command never end and never give other result them errors...

But i remember that on some previous version of ilo this command work.

**Comment by ariael** [comment]
I think that problem have connection with update iLO to version 1.40+ and change RedFish API version!!

**Comment by hp-powershell** [comment]
Hi,

This cmdlet takes time to execute because it traverses from the root node till the last node. But inspite of the error you will still get the result for all the reachable nodes. 

Thanks
Hema

**Comment by ariael** [comment]
Hi - before iLO 1.40 time for run this cmdlet was 3-4 minutes approx. After update to 1.40 this cmdlet never end!

**Comment by hp-powershell** [comment]
Hi,

Could you please share the machine details like server model etc. Are you observing this in particular server or on all the server with iLO firmware 1.43?

Thanks,
Hema

**Comment by ariael** [comment]
Machine is DL360 (lots of machine), iLO 1.43.
Unfortunately i don't know how exactly log cmdlets from HPERedfishCmdlets... Standard way don't work very well... I can send you transcript, but i think that isn't enough. Pipelining don't work well, normal iLO logging don't write anything.

**Comment by ariael** [comment]
Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4688 char:9
+         Step-ThroughNoteProperties -node $Session.RootData -DOdataId  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4688 char:9
+         Step-ThroughNoteProperties -node $Session.RootData -DOdataId  ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 
Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 
Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties
 
Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

Step-ThroughNoteProperties : Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for 
the SSL/TLS secure channel."
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:4545 char:33
+ ...             Step-ThroughNoteProperties -node $temp -DOdataId $DOdataI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Step-ThroughNoteProperties

**Comment by hp-powershell** [comment]
Hi

From the error I see that the iLO does not have valid certificate in which case you can use "DisableCertificateAuthentication" parameter with all the cmdlets or reload the certificate.

There is no logging cmdlets for HPERedfishCmdlets module available.

Thanks,
Hema
