### ISSUE TITLE
Problem with Set-HPEILOAccessSetting -ServerFQDN / -Servername

### ISSUE THREAD

**Issue by Michel-CO** [HewlettPackard/PowerShell-ProLiant-SDK#31]
Hey,

when I try to configure ILO5 (1.45), I can not set FQDN / Servername with "Set-HPEiLOAccessSetting -ServerFQDN / -ServerName".

_$X = $ILOCon | Set-HPEiLOAccessSetting -ServerName $Servername -Verbose
VERBOSE: Performing the operation "Set-HPEiLOAccessSetting" on target "IP: ".
VERBOSE: [Set-HPEiLOAccessSetting] Executing the cmdlets with 1 task serially.
VERBOSE: [Set-HPEiLOAccessSetting][ILO]: Validating Cmdlet supportability.
VERBOSE: [Set-HPEiLOAccessSetting][ILO]: Validating parameter supportability.
$X.StatusInfo.Message
The parameter(s) listed in AffectedAttribute are not supported on iLO5. For more details about supported parameters, see the cmdlet help.
$X.StatusInfo.Message
The parameter(s) listed in AffectedAttribute are not supported on iLO5. For more details about supported parameters, see the cmdlet help._

_$X = $ILOCon | Set-HPEiLOAccessSetting -ServerFQDN $SRVFQDN -Verbose
VERBOSE: Performing the operation "Set-HPEiLOAccessSetting" on target "IP: ".
VERBOSE: [Set-HPEiLOAccessSetting] Executing the cmdlets with 1 task serially.
VERBOSE: [Set-HPEiLOAccessSetting][ILO]: Validating Cmdlet supportability.
VERBOSE: [Set-HPEiLOAccessSetting][ILO]: Validating parameter supportability.
$x.StatusInfo.Message
The parameter(s) listed in AffectedAttribute are not supported on iLO5. For more details about supported parameters, see the cmdlet help._

How can I solve the problem?

Thanks

Michel

**Comment by hp-powershell** [comment]
Hi Michel,

The parameters "ServerName" and "ServerFQDN" are not supported on iLO5 as they are read only properties in Redfish. Hence, you can do a Get and cannot Set it.

Thanks

**Comment by Michel-CO** [comment]
Hey,

that means, I have to continue to use the old CMDLets for the configuration? Will that be in future for HPEILOCMDLets?

Thanks
