### ISSUE TITLE
Update-HPEiLOFirmware cmdlet problem

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#33]
Standard iLO update (BIOS have same problem)... And this is result.

VERBOSE: Performing the operation "Update-HPEiLOFirmware" on target "IP: 2.173.212.36".
WARNING: Update is in progress, this might take several minutes.
VERBOSE: [Update-HPEiLOFirmware] Executing the cmdlets with 1 task serially.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Validating Cmdlet supportability.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Validating parameter supportability.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Forming Request body to be posted.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Uploading the file.
Update-HPEiLOFirmware : [2.173.212.36]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

And script continue - none problem with connectors, none terminated session, iLO is 1.40 and i try update to 1.43.

**Comment by hp-powershell** [comment]
Hi,

This issue might occur at times when the service is unavailable at that moment. It should work when you retry it.

Thanks
