### ISSUE TITLE
Update-HPEiLOFirmware cmdlet problem

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#34]
Standard iLO update (BIOS have same problem)... And this is result.

VERBOSE: Performing the operation "Update-HPEiLOFirmware" on target "IP: 2.173.212.36".
WARNING: Update is in progress, this might take several minutes.
VERBOSE: [Update-HPEiLOFirmware] Executing the cmdlets with 1 task serially.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Validating Cmdlet supportability.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Validating parameter supportability.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Forming Request body to be posted.
VERBOSE: [Update-HPEiLOFirmware][2.173.212.36]: Uploading the file.
Update-HPEiLOFirmware : [2.173.212.36]: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.

And script continue - none problem with connectors, none terminated session, iLO is 1.40 and i try update to 1.43.
------------------------------------------------------------------------------------------------------

**Comment by ariael** [comment]
Case closed with recommend:
Hi,

This issue might occur at times when the service is unavailable at that moment. It should work when you retry it.

Thanks

**Comment by ariael** [comment]
Sorry - this don't work. I have maybe 30-40 tests with same result. In this time machine don't have another task. Repeat cmdlet don't work, repeat all script don't work.

**Comment by hp-powershell** [comment]
Hi,

Can you please enable the log using Enable-HPEiLOLog and share the log details along with the machine details. Are you observing this on a particular machine or all the machines while updating?

Thanks.
