### ISSUE TITLE
Unable to establish connection to a Synergy 480 Gen10 with HPE iLOcmdlets 2.2.0.0

### ISSUE THREAD

**Issue by SupraOva** [HewlettPackard/PowerShell-ProLiant-SDK#39]
Hi guys,

It's all in the title, I don't known if it's a known issue but we can't establish a connection to our Synergy Gen10 (Synergy 3820C 10/20Gb CNA) iLO 1.46 with the module iLOcmdlets 2.2.0.0.

Command : `Connect-HPEiLO -IP <iLO_IP> -Username <username> -Password <password> -DisableCertificateAuthentication
`

See error below : 

> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Parameter processing started. 
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - IP.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - Username.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - Password.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - Credential.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - XAuthToken.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - Timeout.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - iLOResetWaitTimeout.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - DisableCertificateAuthentication.
> 2019-12-13 12:52:00,259 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Processing parameter - Force.
> 2019-12-13 12:52:00,291 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO] Executing the cmdlets with 1 task serially.
> 2019-12-13 12:52:00,291 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO][iLO_IP][GetCommunicationModel]: Begin
> 2019-12-13 12:52:00,291 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO][iLO_IP][GetCommunicationProtocolType]: Begin
> 2019-12-13 12:52:00,291 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO][iLO_IP][GetCommunicationProtocolType]: Getting iLO information.
> 2019-12-13 12:52:00,291 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO][iLO_IP][GetCommunicationProtocolType]: URL:https://iLO_IP/xmldata?item=All
> 2019-12-13 12:52:00,306 HPE.Framework.Logging.Logger.LogMessage INFO - [Connect-HPEiLO][iLO_IP][GetCommunicationProtocolType]: Either XML data could not be read or the target is non Proliant hence attempting to get target information from SMBIOS Record.
> 2019-12-13 12:52:00,306 HPE.Data.iLOConnector.RIS.LogHelper.LogMessage INFO - [iLO_IP][GetiLOInfo]: Begin
> 2019-12-13 12:52:00,322 HPE.Data.iLOConnector.RIS.LogHelper.LogMessage INFO - [iLO_IP][GetiLOInfo]: Getting server details.
> 2019-12-13 12:52:01,289 HPE.Data.iLOConnector.RIS.LogHelper.LogMessage INFO - [iLO_IP][GetiLOInfo]: Server Generation is GEN10 and EISA ID is $0E11084C.
> 2019-12-13 12:52:01,289 HPE.Data.iLOConnector.RIS.LogHelper.LogMessage INFO - [iLO_IP][GetiLOInfo]: Getting iLO firmware version and iLO Generation details.
> 2019-12-13 12:52:01,414 HPE.Framework.Logging.Logger.LogMessage ERROR - [iLO_IP][Connect-HPEiLO]: 
> ExceptionMessage:Input string was not in a correct format..
> InnerException:.
> StackTrace:   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
>    at System.Convert.ToDouble(String value)
>    at HPE.Data.iLOConnector.EISA.ServerVendor.GetiLOInfo(String inputIP, String username, String password, String xAuthToken, Int32 timeout, Boolean certFlag)
>    at HPE.Framework.Communication.CommunicationFactory.GetCommunicationProtocolType()
>    at HPE.Framework.Communication.CommunicationFactory.GetCommunicationModel(CmdletRecord cmdletRecord)

In addition, in the xml data file (https://iLO_IP/xmldata?item=All) the section BladeSystem does not report information as on the C7000

```
<BLADESYSTEM>
<BAY>1</BAY>
<MANAGER>
<TYPE>Enclosure Manager</TYPE>
<MGMTIPADDR>0.0.0.0</MGMTIPADDR>
<RACK>1</RACK>
<ENCL/>
<ST>2</ST>
</MANAGER>
</BLADESYSTEM>
```

**Comment by hp-powershell** [comment]
Hi,

This is a known issue that is occurring due to different culture setting in the control panel. The decimal formatting is not '.' in your system. This will be handled in the next release.

Regards,
Hema
