### ISSUE TITLE
Configure groups

### ISSUE THREAD

**Issue by rumart** [HewlettPackard/PowerShell-ProLiant-SDK#4]
Can we have some functions for configuring the Directory Groups through Powershell? I can't find any cmdlet dealing with Groups.

For iLO 4 I've been using a RIBCL command/script, but this doesn't seem to support the new privileges in iLO 5.

If there's no Redfish method for configuring groups, where can I request it to be added?

**Comment by hp-powershell** [comment]
This is because of unavailability of iLO5 redfish interfaces from iLO5 version. Tentatively it will be fixed in 1HCY19.

**Comment by g4rpch** [comment]
Any news about this issue?

**Comment by hp-powershell** [comment]
Fixed in latest release of 2.2.0.0 version.
