### ISSUE TITLE
Reset-HPEiLO cmdlets

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#40]
HW 360 Gen10, iLO5 2.1, BIOS U32 v2.22 (11/13/2019)
This cmdlets haven't created lots of code...
----------------------------------------------------------------

$temp = Reset-HPEiLO -Connection $connection -Device Server -Confirm:$false
$temp.StatusInfo.Message
'ActionParameterUnknown'

$temp = Reset-HPEiLO -Connection $connection -Device Both -Confirm:$false
$temp.StatusInfo.Message
'ActionParameterUnknown'

$temp = Reset-HPEiLO -Connection $connection -Device iLO -Confirm:$false
$temp.StatusInfo.Message
'ResetInProgress'

And i wish you close happy one year event without any push any repair or new code...
HPe have lots of promises before we buy this product and reality is very very sad.

**Comment by hp-powershell** [comment]
Hi,

The cmdlet works as expected on iLO firmwares below 2.10. There were some changes made in the redfish URI and the parameter that it accepts in 2.10 hence the error. This has been taken care in the code and will be available in the next release of HPEiLOCmdlets. Sorry for the inconvenience caused.

Thanks

**Comment by ariael** [comment]
Hi,
Sorry, but iLO 2.10 is in matrix baseline needed by HPe. HPEiLOCmdlets is
from same source - oficial HPe.
I need repair this problem from HPe.

**Comment by hp-powershell** [comment]
Hi,

The fix for this cmdlet will be available in the next release. You can use Set-HPEiLOServerPower cmdlet as an alternative which does the same as above.

For Device option 'Both' - $connection | Set-HPEiLOServerPower -Power AuxCycle  
For Device option 'Server' - $connection | Set-HPEiLOServerPower -Power ColdBoot 

Regards,
Hema
