### ISSUE TITLE
Error using Set-HPERedfishData for iLO5 in Synergy 

### ISSUE THREAD

**Issue by rodolfojmatos** [HewlettPackard/PowerShell-ProLiant-SDK#41]
I am using the function Set-iLOUserAccountExample6 from the examples to change just the password from an iLO user account. (But I am using an SSO connection, so that part of the script I have changed)
The problem is, when reach the Line:
$ret = Set-HPERedfishData -odataid $requiredAccountOdataId -Setting $user -Session $session

it throws an error:
_Write-Verbose : Cannot bind argument to parameter 'Message' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:1378 char:35_
+                     Write-Verbose $_.Message
+                                   ~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Verbose], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.WriteVerboseCommand

**Let me know what need to change in the script, and if it should work on Synergy model.**

**Comment by hp-powershell** [comment]
Hi  ,

Thanks for writing to us . 

Synergy should work , there is no restriction for that variant. 

Kindly try the below when using example 2
In the example 2, in the section 

$priv = @{}
            $priv.Add('VirtualMediaPriv',$false)
            $priv.Add('UserConfigPriv',$false)
                
            $hp = @{}
            $hp.Add('Privileges',$priv)
        
            $oem = @{}
            $oem.Add('Hp',$hp)
    
            $user = @{}
            $user.Add('Oem',$oem)

Kindly change 
 $oem.Add('Hp',$hp)
 
to 
 $oem.Add('Hpe',$hp) 

and try whether that resolves the issue you are facing. 

Kindly let us know .

Thanks & Regards,
Powershell Team
