### ISSUE TITLE
New-HPESALogicalDrive - DataDrive attribute does not processes the variable value

### ISSUE THREAD

**Issue by SahilMutha** [HewlettPackard/PowerShell-ProLiant-SDK#43]
I am using the New-HPESALogicalDrive to create the Logical Drive in DL360. As per the syntax for -DataDrive, I am using double dimension array for it. But it is not able to create the logical drive. Below is my code snippet.

`$SA_PhysicalDrives = (Get-HPESAPhysicalDrive -Connection $Connect_SA -ControllerLocation $SA_ControllerLocation).PhysicalDrive.Location`

`$DrivesToBeAttached = @($SA_PhysicalDrives[0..($NoOfPhysicalDrives-1)]) # I am doing this, since $NoOfPhysicalDrives is a user input.`

`New-HPESALogicalDrive -Connection $Connect_SA -LogicalDriveName $LogicalDriveName -ControllerLocation $SA_ControllerLocation -Raid $RAID -DataDrive @(,$DrivesToBeAttached)`

After running the command like this, when I do Get-HPESALogicalDrive, I get the output like below. Also after reboot of the server, the drive is deleted automatically.

![image](https://user-images.githubusercontent.com/31176140/80685666-2fa97500-8ae5-11ea-8492-70babc285fae.png)

But, when I run it without having a variable, it gives a proper output.

`New-HPESALogicalDrive -Connection $Connect_SA -LogicalDriveName $LogicalDriveName -ControllerLocation $SA_ControllerLocation -Raid $RAID -DataDrive `@(,@("1I:1:1","1I:1:2"))`
Output:
![image](https://user-images.githubusercontent.com/31176140/80685839-68494e80-8ae5-11ea-89d7-4630bf491055.png)

**Comment by hp-powershell** [comment]
Hi ,

If the created drive is not appropriate , until you reboot the server it still remains in the smartstorageconfig but once the system is rebooted any wrongly configured logical drive will be automatically erased . 

this is by behavior of iLO .

Data Drive format has to be appropriate for it to be accepted by the server . Your 2nd request does has it in right format but the first one might have added extra characters while it was getting converted ,Make sure no extra characters are in place .

Even after every parameter is correct and if the issue persists kindly raise an issue , we have a SA cmdlet release planned we can address it over there . 

Thanks & Regards,
Powershell Team
