### ISSUE TITLE
Import-HPEiLOLDAPCACertificate generates invalid request

### ISSUE THREAD

**Issue by ibauersachs** [HewlettPackard/PowerShell-ProLiant-SDK#46]
Using HPEiLOCmdlets/3.0.0.0 Import-HPEiLOLDAPCACertificate fails to import the certificate.

```
$> Import-HPEiLOLDAPCACertificate -Connection $connect -Certificate $cert -OutputType RawResponse -Verbose

VERBOSE: Performing the operation "Import-HPEiLOLDAPCACertificate" on target "ilo.example.com".
VERBOSE: Executing the cmdlets with 1 task serially.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Validating Cmdlet supportability.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Checking for iLOGeneration, Model and Firmware for Cmdlet Supportability.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Validating parameter supportability.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Getting url value from resource instance.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Creating Redfish request.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Retrieving URL's from parameter mapper.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Forming JSON payload for corresponding URL.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Creating Redfish request.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Sending Redfish request to PATCH/POST/DELETE the JSON payload.
VERBOSE: [Import-HPEiLOLDAPCACertificate][ilo.example.com][Redfish]: Processing JSON response.
Target: ilo.example.com
URL: https://ilo.example.com/redfish/v1/AccountService/ExternalAccountProviders/LDAP/Certificates/
ContentType: application/json
Response: {"error":{"code":"iLO.0.10.ExtendedInfo","message":"See @Message.ExtendedInfo for more information.","@Message.ExtendedInfo":[{"MessageArgs":["CertificateType"],"MessageId":"iLO.2.13.RequiredPropertyMissing"}]}}
```

Comparing with what happens from the UI, the request seems to be missing the `CertificateType: "PEM"` JSON property.

**Comment by dcasota** [comment]
Guess you were using something like the help code snippet
```
$con = Connect-HPEiLO 10.20.30.40 -Username admin -Password admin123 -DisableCertificateAuthentication
$cert = Get-Content -Path "C:\Users\admin\Downloads\cacertificate.cer" -raw
$out = $con | Import-HPEiLOLDAPCACertificate -Certificate $cert
```
You might check the result when using the entire certificate chain including public key, private key, and root certificates.

Alternatively you could compare the behaviour using the python-redfish-utility https://github.com/HewlettPackard/python-redfish-utility/blob/master/docs/slate/source/includes/_ilocommands.md

hth

**Comment by ibauersachs** [comment]
I looked at the source of the cmdlets: they're autogenerated. This specific one simply misses to include the required `CertificateType` property in the generated JSON.

I've given up using the cmdlets, the next one that isn't working is #47. Whoever designed this obviously didn't bother to test the generated code.

**Comment by dcasota** [comment]
can’t test it. These cmdlets behaviour happen against which iLO license type? https://support.hpe.com/hpesc/public/docDisplay?docId=emr_na-c05269613

**Comment by ibauersachs** [comment]
Advanced.

**Comment by dcasota** [comment]
@hp-powershell @Rajusi can you confirm on this?

**Comment by hp-powershell** [comment]
Hi,

This is an issue in the module occuring on iLO with firmware version >=2.10. CertificateType is a new property that is added and made mandatory in the latest firmwares which got missed in the analysis. Regret the inconvenience.

**Comment by ibauersachs** [comment]
So where's the new version that fixes this? [PSGallery](https://www.powershellgallery.com/packages/HPEiLOCmdlets/3.0.0.0) is still at v3.0.0.0.

Closing issues without actually fixing things: way to go HP 👏🤦‍♂️
