### ISSUE TITLE
Configure LDAP integration

### ISSUE THREAD

**Issue by rumart** [HewlettPackard/PowerShell-ProLiant-SDK#5]
Can we have some functions for configuring the LDAP integrationg through Powershell?

For iLO 4 I've been using a RIBCL command/script, but this has shortcomings for instance when dealing with groups in iLO 5. I've opened an issue for this as well (feel free to combine both in one single issue if  #wanted)

If there's no Redfish method for configuring this integration, where can I request it to be added?

**Comment by hp-powershell** [comment]
Fixed in iLO 2.2.0.0 release.
