### ISSUE TITLE
ILO5 2.30 Get-HPEiLOAccessSetting empty

### ISSUE THREAD

**Issue by Michel-CO** [HewlettPackard/PowerShell-ProLiant-SDK#50]
Hi,
at the moment i test the new ILO5 Firmware 2.30 with Powershell Modules 3.0.0. When take the command "Get-HPEiLOAccessSetting" CMDLet, the output is emtpy.

_$GetAccessSettings = $con | Get-HPEiLOAccessSetting
$GetAccessSettings

AuthenticationFailuresBeforeDelay     :
AuthenticationFailureDelayTimeSeconds :
AuthenticationFailureLoggingThreshold :
FederationEnabled                     :
FederationSupported                   :
FQDN                                  : FQDN
HTTPPort                              :
HTTPProtocolEnabled                   :
HTTPSPort                             :
HTTPSProtocolEnabled                  :
iLOFunctionalityEnabled               :
iLORBSUEnabled                        :
IPMIPort                              :
IPMIProtocolEnabled                   :
MinimumPasswordLength                 : 0
PasswordComplexityEnabled             :
PhysicalMonitorHealthStatusEnabled    :
RIBCLEnabled                          :
RemoteConsolePort                     :
RemoteConsoleProtocolEnabled          :
RemoteConsoleThumbnailEnabled         :
RequireHostAuthentication             :
RequiredLoginForiLORBSU               :
SerialCLISpeed                        :
SerialCLIStatus                       :
SerialCLIUART                         :
SessionTimeoutMinutes                 :
SNMPProtocolEnabled                   :
SNMPPort                              :
SNMPTrapPort                          :
SSHProtocolEnabled                    :
SSDPNotifyIPv6Scope                   :
SSDPNotifyMulticastIntervalSeconds    :
SSDPNotifyTTL                         :
SSDPPort                              :
SSDPProtocolEnabled                   :
SSHPort                               :
VirtualMediaProtocolEnabled           :
VirtualMediaEncryptionEnabled         :
VideoPresenceDetectOverride           :
VideoPresenceDetectOverrideSupported  :
VirtualNICEnabled                     :
VirtualMediaPort                      :
VSPLogDownloadEnabled                 :
WebGUIEnabled                         :
XMLReplyEnabled                       :
SerialOverLANLoggingEnabled           :
VSPDlLoggingEnabled                   :
ServerName                            :
ServerFQDN                            :
IP                                    : localIP
Hostname                              : Hostname
Status                                : OK
StatusInfo                            :_

Please check it.

Thank you

EDIT: I have also tested the new PSModule Version 3.0.0.1.

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us . 

HPEiLOCmdlets 3.0.0.1 is a hot fix release which is released prior to release of iLO FW 2.30 . 

iLO FW 2.30 has introduced a new change in redfish apis w.r.t select queries in URI . Same need to be supported in cmdlets for the cmdlets to provide the desired result . 

We are working on release of hpe iLO cmdlets  to incorporate the iLO FW 2.30 changes . 

You would get the support in our upcoming release .

Thanks & Regards,
Powershell Team
