### ISSUE TITLE
Request for Mac support fro iLO Modules

### ISSUE THREAD

**Issue by ajayvaaka** [HewlettPackard/PowerShell-ProLiant-SDK#54]
## Issue : 

Get-InstalledModule -name HPEiLOCmdlets | import-module

Import-Module: Cannot find drive. A drive with the name '@{Name=HPEiLOCmdlets; Version=3.0.0.0; Type=Module; Description=Scripting Tools for Windows PowerShell ' does not exist.

### OS:

OS : Mac 

### dotnet on Mac

dotnet --version
3.1.402

### Powershell version : 

Name                           Value
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

May I know this module supports Mac OS?

Thanks & Regards
Ajay Vaaka

**Comment by hp-powershell** [comment]
Hi 

Thanks for writing to us . The HPE powershell cmdlets current support matrix is only enabled for windows OS . 

Thanks & Regards,
HPE Powershell Cmdlets Team
