### ISSUE TITLE
No SmartArray controller found, using E208i

### ISSUE THREAD

**Issue by weidi** [HewlettPackard/PowerShell-ProLiant-SDK#55]
I try to create a RAID 1 of two drives connected to an E208i but using Get-HPESAPhysicalDrive gives me "No SmartArray Controller"
Seems like a bug to me?
![image](https://user-images.githubusercontent.com/2188062/102932352-6a12b880-44a0-11eb-89fb-f673e55ae35b.png)
![image](https://user-images.githubusercontent.com/2188062/102932150-08524e80-44a0-11eb-807b-bf544dbd39c1.png)

**Comment by weidi** [comment]
Just adding this as it is happening on multiple servers

![image](https://user-images.githubusercontent.com/2188062/103524530-044e0580-4e7e-11eb-8a05-e468c8f332ca.png)

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us. 

May we know the FW version in the server . 

Thanks & Regards,
Powershell Team

**Comment by weidi** [comment]
iLO is 2.30 and 2.31 
E208i-a SR is 3.00

**Comment by hp-powershell** [comment]
Hi 

With the iLO FW 2.30 there is a change introduced by iLO team w.r.t Redfish URI format . 
Its a major change and it has effected the functioning of the cmdlets . 

Powershell team has planned to provide a release fixing this issue. We are in discussion w.r.t release date . We shall let you know once the release date is finalized . 

Thanks for understanding . 

Thanks & Regards,
Powershell Team

**Comment by weidi** [comment]
ok, i can confirm that it is working on 2.19, would be great to have a workaround for this even before you release a new version.
If you want i can test the new version as well.

**Comment by hp-powershell** [comment]
Hi ,

You are right , problem is seen only on 2.30 and above as the changes iLO team has introduced is from iLO FW 2.30 . There is no work around as of now as the changes are introduced in very basic level of redfish format usage which requires cmdlets to change the redfish format structure in codebase . We are targeting this release ASAP looking at the huge impact the iLO change has brought in . We would let you know once we have a final date of release . Released version will be QA certified too . 

Thanks & Regards,
Sahana

**Comment by klaspihl** [comment]
@hp-powershell 
Still an issue with version 1.0.0.2  of HPESmartArrayCmdlets with iLO 2.30+
My DL360 Gen10 with iLO Firmware Version 2.65 and P408i-a FW 5.32

```powershell
PS C:\> get-command Get-HPESALogicalDrive

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-HPESALogicalDrive                              1.0.0.2    HPESmartArrayCmdlets

PS C:\> Get-HPESALogicalDrive -Connection $connectSA | Select-Object -ExpandProp

      Category Message
      -------- -------
Unavailability No Smart Array controller found at the target server "ProLiant DL360 Gen10".
```

**Comment by hp-powershell** [comment]
Hi ,

We did check this on latest released version with a server having E208i controller , we are able to capture the details as below. 
![image](https://user-images.githubusercontent.com/14983737/210312989-73375f87-69c3-4b71-88f7-115ba6149fc2.png)


kindly let us know whether you are still seeing issue  

Thanks & Regards,
Powershell Team

**Comment by klaspihl** [comment]
> We did check this on latest released version with a server having E208i controller , we are able to capture the details as below. ...
> Thanks & Regards, Powershell Team

Download link at https://www.hpe.com/servers/powershell returns **Bad Request**
No releases or packages at Github and latest commit is from oct 20 **2021**

@hp-powershell  Where do we find the working version you are referring to?
