### ISSUE TITLE
Set-VirtualMedia

### ISSUE THREAD

**Issue by ehsanijavad** [HewlettPackard/PowerShell-ProLiant-SDK#56]
Hi
First of all thank you for your scripts.
Could you please write what is the error?

 Function Mount-VirtualMedia {
        
    Param (    
        
        [system.object]$IsoUrl = $null,
        $IloSession,
        [system.object]$BootOnNextReset = $null
    
    )

    # NOTE: if ISO URL is blank and BootOnNextReset are blank/null, the virtual media is unmounted
    
    # Connect session
    #$session = Connect-HPERedfish -Address $Address -Credential $Credential

    $managers = Get-HPERedfishDataRaw -odataid '/redfish/v1/Managers/' -DisableCertificateAuthentication -Session $IloSession
    foreach($mgr in $managers.Members.'@odata.id')
    {
        
        $mgrData = Get-HPERedfishDataRaw -odataid $mgr -DisableCertificateAuthentication -Session $IloSession -ErrorAction SilentlyContinue
        # Check if virtual media is supported
        if($mgrData.PSObject.Properties.name -Contains 'VirtualMedia' -eq $false)
        {
            # If virtual media is not present in links under manager details, print error
            Write-Host 'Virtual media not available in Manager links'
        }
        else
        {
            
            $vmOdataId = $mgrData.VirtualMedia.'@odata.id'
            $vmData = Get-HPERedfishDataRaw -odataid $vmOdataId -DisableCertificateAuthentication -Session $IloSession
            foreach($vm in $vmData.Members.'@odata.id')
            {
                $data = Get-HPERedfishDataRaw -odataid $vm -DisableCertificateAuthentication -Session $IloSession
                # select the media option which contains DVD
                if($data.MediaTypes -contains 'DVD')
                {
                    # Create object to PATCH to update ISO image URI and to set
                    if($IsoUrl -eq $null)
                    {
                        $mountSetting = @{'Image'=$null}
                    }
                    else
                    {
                        $mountSetting = @{'Image'=[System.Convert]::ToString($IsoUrl)}
                    }
                    if($BootOnNextReset -ne $null -and $IsoUrl -ne $null)
                    {
                        # Create object to PATCH
                        #$oem = @{'HpE'=@{'BootOnNextServerReset'=[System.Convert]::ToBoolean($BootOnNextReset)}}

                        $oem = @{'Hp'=@{'BootOnNextServerReset'=[System.Convert]::ToBoolean($BootOnNextReset)}}

                        $mountSetting.Add('Oem',$oem)
                    }
                    # PATCH the data to $vm odataid by using Set-HPERedfishData
                    #Disconnect-HPERedfish -Session $session
                    $ret = Set-HPERedfishData -odataid $vm -Setting $mountSetting -Session $IloSession
                    
                    # Process message(s) returned from Set-HPERedfishData
                    if($ret.error.'@Message.ExtendedInfo'.Count -gt 0)
                    {
                        foreach($msgID in $ret.error.'@Message.ExtendedInfo')
                        {
                            $status = Get-HPERedfishMessage -MessageID $msgID.MessageID -MessageArg $msgID.MessageArgs -Session $IloSession
                            $status
                        }
                    }
                    Get-HPERedfishDataRaw -odataid $vm -DisableCertificateAuthentication -Session $IloSession -ErrorAction SilentlyContinue
                }
            }        
        }
    }
    # Disconnect session after use
    Disconnect-HPERedfish -Session $IloSession 
}

 Import-Module HPERedfishCmdlets
$cre_OneView = Get-Credential
Connect-HPOVMgmt -Hostname lab-oneview.lab.local -Credential $cre_OneView

$srv = Get-HPOVServer
$IsoUrl = 'http://192.168.1.89/ISOs/ESXi-7.iso'
$IloSession = $srv | Get-HPOVIloSso -IloRestSession

Mount-VirtualMedia -IsoUrl $IsoUrl -IloSession $IloSession -BootOnNextReset $true

#-------------------------------------------------
The odata id is invalid
At C:\Program Files\WindowsPowerShell\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets.psm1:5107 char:9
+         throw $(Get-Message('MSG_INVALID_ODATA_ID'))
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The odata id is invalid:String) [], RuntimeException
    + FullyQualifiedErrorId : The odata id is invalid

Thank you in advance for your help.

**Comment by hp-powershell** [comment]
Hi ,

Kindly use the cmdlet 
Mount-HPEiLOVirtualMedia
from HPEiLOCmdlets 3.3 , below is the link to download
https://www.powershellgallery.com/packages/HPEiLOCmdlets/3.3.0.0

connect-hpeilo can be used to connect to the server and above cmdlet to mount , 
let us know and raise a new ticket against ilocmdlets, if the cmdlets are not yielding right solution . 

Note: Connect-hpeilo works with xauthtoken too which can be got from OV if in case you dont have server credentials 

Thanks & Regards,
Powershell Team
