### ISSUE TITLE
HPEiLOCmdlets and Server Power Information

### ISSUE THREAD

**Issue by lelloz0** [HewlettPackard/PowerShell-ProLiant-SDK#59]
I couldn't find any cmdlet part of the latest version of the HPEilocmdlets modules 3.0.0.1 that returns the Server Power. Can you please check and ensure this is added to Connect-HPEiLO or Get-HPEiLOServerInfo ? Thanks

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us . 

Kindly check whether 
Get-HPEiLOServerPower provides you the info you are looking for . 

Thanks & Regards,
Powershell Team

**Comment by lelloz0** [comment]
@hp-powershell that does it, I totally overlooked it. Thanks!
