### ISSUE TITLE
Add Fan Information to HPESysInfocmdlets

### ISSUE THREAD

**Issue by lelloz0** [HewlettPackard/PowerShell-ProLiant-SDK#60]
The [HPESysInfocmdlets](https://www.powershellgallery.com/packages/HPESysInfoCmdlets/1.5.0.2) is a great in band tool we use to collect information within the OS of Gen10 Servers to pass back to SCCM and so far I've noticed the module is lacking of a functions that retrieves the following information

- Fan (there's nothing returned for the FANs. Ideally it should return all the info available in the GUI)
- iLO Licence type (for example, Advanced, etc)
- iLO Unique identifier

Thanks!

**Comment by hp-powershell** [comment]
Hi ,

Our team don't handle hpesysinfocmdlets 
currently the ownership is with 
katy.huang@hpe.com

kindly write to them .

Thanks & Regards,
Powershell Team
