### ISSUE TITLE
HPESysInfocmdlets and HPEiloCmldets missing iLO Date/Time

### ISSUE THREAD

**Issue by lelloz0** [HewlettPackard/PowerShell-ProLiant-SDK#61]
Both in band and out of band modules are missing an important information that would be great to have: the iLO date/Time - that's useful to troubleshoot any clock syncing drifts - can it please be added to both modules? Thanks

**Comment by hp-powershell** [comment]
Hi ,

Our team don't handle hpesysinfocmdlets 
currently the ownership is with 
katy.huang@hpe.com

kindly write to them .

Thanks & Regards,
Powershell Team
