### ISSUE TITLE
New version 3.1 iLOcmdlets

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#62]
Hi,
I search information about changes in this version. But only information what i found is:

**Enhanced 10 existing cmdlets in the HPEiLOCmdlets module. 
Added 1 new cmdlet in the HPEiLOCmdlets module.**

Have you some better information about this please?
Best Regards
Ari

**Comment by hp-powershell** [comment]
Hi Ari,

Kindly be specific on what information you are looking for . 

To summarize the build.

This new release has the iLO FW 2.30 redfish schema change support so more than 56+ cmdlets which were not providing any response earlier will provide the response .

Also we have included few new features of FW 2.30 in existing cmdlets and added a new cmdlet as below.

Get-HPEiLOSNMPAlertSetting
Set-HPEiLOSNMPAlertSetting
Get-HPEiLOSystemInfo
Get-HPEiLOUser
Get-HPEiLOFirmwarePolicy
Set-HPEiLOFirmwarePolicy
Get-HPEiLOInfo
Get-HPEiLOInfo
Get-HPEiLOTemperature
Get-HPEiLOServerInfo

Get-HPEiLOFirmwareCapabilities
being the 1 new cmdlet added.

Thanks & Regards,
Powershell Team
