### ISSUE TITLE
iLO 2.33 have incompatibility issue with module HPESmartArrayCmdlets

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#63]
Hi,
I found another really critical issue. After long wait (6 months) for update iLO cmdlets to version 3.1 and unfreeze our several thousand production servers locked on iLO 2.33 i found this:

Open call to SmartArray with iILO 2.14:
`Get-HPESAConfigurationStatus -Connection $script:connectionSA
IP                  : 1.1.1.1
Hostname            : my.dc.com
Status              : Warning
ConfigurationStatus : {@{ControllerLocation=Slot 0; ControllerModel=HPE Smart Array P408i-a SR Gen10; ETag=; Severity=; MessageId=Base.1.0.Success; Message=; Description=; MessageArgs=; RelatedProperty=; Resolution=}}
StatusInfo          : @{Category=Unknown; Message=Unable to process the MessageId.} `

This is standard response

And after i upgrade iLO to 2.33:
`Get-HPESAConfigurationStatus -Connection $script:connectionSA
IP            Hostname                        Status StatusInfo
--            --------                        ------ ----------
1.1.1.1 my.dc.com  Error @{Category=Unavailability; Message=No Smart Array controller found at the target server "ProLiant DL360 Gen10".} `

And of course without status, position and etc. i can't run another SmartArrayCmdlets
Problem tested on several servers Gen 10 - same behavior.

p.s. After downgrade all work again....

**Comment by hp-powershell** [comment]
Hi Ari,

We have released HPEiLOCmdlets 3.1 version and not SACmdlets .
The cmdlet you are referring to above is from smart array module of cmdlets and not iLO cmdlets module . The issue with iLO FW 2.30 requires different fix in iLO Cmdlets and different fix in SA cmdlets . Hence version 3.1 of ILOcmdlets wouldnt solve the SA cmdlet issue . 

In SA module , iLO FW 2.30 issue has effected all the 21 cmdlets of SA and we are in progress with code module changes for all the 21 cmdlets . We are already mid way through the code modification (which we took up immediately post releasing iLO version 3.1 as our top priority currently). Parallel testing from QA is also in progress . 

HPESmartArrayCmdlets 1.0.0.2 is scheduled to be released for end of this month . 

Thanks & Regards,
Powershell Team

**Comment by ariael** [comment]
Ok. i understood...
And for Bios cmdlets is situation same i presume...

**Comment by hp-powershell** [comment]
Hi ,

BIOS cmdlets are being checked against iLO FW 2.30 . So far we have not got any report of the problem w.r.t iLO FW 2.30 select query change . 
if in case you have come across in your script anything related to same you can let us know . 

BIOS Cmdlets follow a different approach is coding which makes it less vulnerable to the iLO FW 2.30 change. 

Thanks & Regards,
Powershell Team

**Comment by hp-powershell** [comment]
Hi Ari,

Post we have fixed all cmdlets with iLO FW 2.30 issue ,
We have identified a major issue with New-hpesalogicaldrive cmdlet where the cmdlet is not creating any drives though there is no error. It's a major find hence we are including this too in this release , that has pushed the date to next week as we need to complete the qualification cycle for same. 

Thanks for understanding. 

Thanks & Regards,
Powershell Team

**Comment by ariael** [comment]
Hi teams,

Can i ask about situation with SA Cmdlets?

**Comment by hp-powershell** [comment]
Hi Ari ,

It is officially released.
https://www.powershellgallery.com/packages/HPESmartArrayCmdlets/1.0.0.2

Thanks & Regards,
Powershell Team

**Comment by ariael** [comment]
Hi thanks for message...

Where i can report error with this new version?

**Comment by hp-powershell** [comment]
Hi Ari,

Kindly provide the detail of the issue. 

You can enable the log and share the log too with the cmdlets error. 

Also, provide the server details and controller details. 

Thanks & Regards,
Powershell Team

**Comment by ariael** [comment]
Hi,
I have serious problem with Show licence. This is cycled and every few second show another window. Press ACCEPT is not accepted :)
For me and now i temporary solve this problem by disable code for show window in your script, but for sure better solution is from your team....

For clarify - i don't use standard "module directory" in program files etc. I use subdirectories in my script for all modules and call all part by cmdlets import-module and path...
This is for achieve "copy script directory and run everywhere" option for my script - without needed standard installation of any part....

**Comment by hp-powershell** [comment]
Hi Ari,

We were not able to reproduce this condition. 

The license window is a one-time popup which when accepted doesn't come another time. 

Could you please help us with the details of your script so that we run the same and see if we can replicate this. 

Also kindly show the screenshot of the pop ups which is interrupting the execution more than once.

Thanks & Regards,
Powershell Team

**Comment by ariael** [comment]
`
try {
    remove-module -Name HPEiLOCmdlets -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
    remove-module -Name HPEBIOSCmdlets -ErrorAction SilentlyContinue -WarningAction SilentlyContinue
    write-host 'Module removed'
}
catch {
    write-host 'Module is not in memory'
}

import-module -Name .\Modules\HPEiLOCmdlets\3.1.0.0\HPEiLOCmdlets.psd1 -RequiredVersion 3.1.0.0 -Force
Import-Module -Name .\Modules\HPEBIOSCmdlets\3.0.0.0\HPEBIOSCmdlets -RequiredVersion 3.0.0.0 -Force
Import-Module -Name .\Modules\HPESmartArrayCmdlets\1.0.0.2\HPESmartArrayCmdlets -Force
import-module -Name .\Modules\DHLRedFishCmdlets\1.1\DHLRedFishCmdlets -Force
import-module -Name .\Modules\HPERedfishCmdlets\1.1.0.0\HPERedfishCmdlets -Force
`

Hi 
This is part of my code with module work.
Any of this module was never installed by "standard way" (as run MSI), exist only in subdirectory and run by this code.
After change version 1.0.0.1 to 1.0.0.2 (SmartArray), i was start see cycleing window with licence agreement.
I think, in your code want save some variable - and this is not happens.

p.s. you can see, that you have change for your new version hpeilocmdlets 3.1 - i must use construct ".\Modules\HPEiLOCmdlets\3.1.0.0\HPEiLOCmdlets.psd1" - without .psd1 this NOT working! Something is changed and wrong.

**Comment by hp-powershell** [comment]
Hi Ari,

we have couple of questions as below. 

So you have downloaded the MSI's from the support hpe portals and you have installed the modules ?
Or you have used Install-Module and have installed all the modules before executing your scripts right ?

in addition to your scripts , we tried below
import-module HPEILOCmdlets
post i install i am able to import without any error also license popup is encountered only once per product . ie one license popup for iLO similarly one license for BIOS, One license popup for SMart array and so on . 

if the installation happens mutliple times then the license popup would also encounter multiple times if versions are different . 

Thanks & Regards,
Powershell Team
