### ISSUE TITLE
New-HPESALogicalDrive strange error - i don't understood what do you means

### ISSUE THREAD

**Issue by ariael** [HewlettPackard/PowerShell-ProLiant-SDK#66]
Hi,
I try lots of variants and always i get this return...

Part of the scripts:

$selecteddrive = @(,@("1I:3:3","1I:3:4"))
$result = New-HPESALogicalDrive -Connection $script:connectionSA -ControllerLocation $locationSA -LogicalDriveName System1 -Raid $raid -DataDrive $selecteddrive -ErrorAction Stop

New-HPESALogicalDrive : Failed for 7.245.109.4: Object reference not set to an instance of an object.
At line:1 char:11
+ $result = New-HPESALogicalDrive -Connection $script:connectionSA -Con ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-HPESALogicalDrive], Exception
    + FullyQualifiedErrorId : HPE.SA.Cmdlet.NewHPESALogicalDrive

**Comment by ariael** [comment]
Same server, more info about errors:

`Get-HPESAConfigurationStatus -Connection $script:connectionSA

IP                  : 7.xxx.xxx.4
Hostname            : usmxxxxx-r.dc.com
Status              : Warning
ConfigurationStatus : {@{ControllerLocation=Slot 0; ControllerModel=; ETag=BFBE6A20; Severity=; MessageId=SmartStorageMessages.2.0.1.CanSetEditableLogicalDriveRAIDLevelUnsupportedDriveCount; Message=;     
                      Description=; MessageArgs={"LogicalDriveName":"System1"}; RelatedProperty=#/LogicalDrives/0; Resolution=}}
StatusInfo          : @{Category=Unknown; Message=Unable to process the MessageId.}



$resultSA = Get-HPESAConfigurationStatus -Connection $script:connectionSA
$Resultsa.ConfigurationStatus


ControllerLocation : Slot 0
ControllerModel    :
ETag               : BFBE6A20
Severity           :
MessageId          : SmartStorageMessages.2.0.1.CanSetEditableLogicalDriveRAIDLevelUnsupportedDriveCount
Message            :
Description        :
MessageArgs        : {"LogicalDriveName":"System1"}
RelatedProperty    : #/LogicalDrives/0
Resolution         :


$resultSA.StatusInfo

Category Message
-------- -------
 Unknown Unable to process the MessageId.`

**Comment by hp-powershell** [comment]
Hi,

Kindly try the same with our latest released version of smart array cmdlets which is HPESmartArrayCmdlets 1.0.0.2 . If the issue persists kindly provide the log file and the cmdlet and the result. 

Thanks & Regards,
Powershell Team

**Comment by hp-powershell** [comment]
Hi,

Kindly try the same with our latest released version of smart array cmdlets which is HPESmartArrayCmdlets 2.0 . If the issue persists kindly provide the log file and the cmdlet and the result.

Thanks & Regards,
Powershell Team
