### ISSUE TITLE
Sample script:   HPEiLO/3.0/EstablishingConnection.ps1 logic issue when iterating over only one IP address

### ISSUE THREAD

**Issue by ripowercat** [HewlettPackard/PowerShell-ProLiant-SDK#67]
The logic appears to be wrong in the aforementioned script when iterating over only one IP.  

	#List of IP's that could not be connected
	if($Connection.count -ne $inputcsv.IP.count)

Always fails as $Connection.count is Null when only one IP is pulled from the CSV file and only one connection is made.  This works fine when more than one connection is made.

Here is how I fixed this:

#List of IP's that could not be connected

	if(($Connection.count -ne $inputcsv.IP.count) -and ($Connection.count -ne $null))

**Comment by hp-powershell** [comment]
Hi ,

Kindly check with the newly released versions. 
We are unable to reproduce the issue mentioned above on new versions. 

Thanks & Regrards,
Powershell Team
