### ISSUE TITLE
Missing Disable-HPEiLOSecurityDashboardSetting option for SNMPv1

### ISSUE THREAD

**Issue by storagemike** [HewlettPackard/PowerShell-ProLiant-SDK#68]
Hi
There is no documented option to set to ignore the security dashboard alert status for SNMPv1.  I've found most of others, but this seems to have been omitted. It's not in the example https://github.com/HewlettPackard/PowerShell-ProLiant-SDK/blob/master/HPEiLO/3.0/SecurityDashboardSettings.ps1 either.  Please could this be added?

**Comment by hp-powershell** [comment]
Hi ,

Thanks for pointing it out . 

We shall look into it as an enhancement and see about implementation . 

Thanks & Regards,
Powershell Team

**Comment by hp-powershell** [comment]
Hi,

We just investigated further and here is what you are asking for 
# Disable SNMPv1 Alerts and Requests
Set-HPEiLOSNMPAlertSetting -Connection $iLO_Connection -SNMPv1Trap Disabled -SNMPv1Enabled Disabled

Thanks & Regards,
Powershell Team
