### ISSUE TITLE
Unable to create multiple Logical volumes from PowerShell

### ISSUE THREAD

**Issue by dbarstad** [HewlettPackard/PowerShell-ProLiant-SDK#70]
Error generated when creating creating multiple logical volumes as noted below:

     + CategoryInfo          : InvalidOperation: (:) [New-HPESALogicalDrive], Exception
    + FullyQualifiedErrorId : HPE.SA.Cmdlet.NewHPESALogicalDrive 

First volume creates properly.   Any subsequent create attempt returns this error until host is rebooted and previously volume generated.

HPEiLOCmdlets  : 3.1.0.1
HPESmartArrayCmdlets : 1.0.0.2
SmartArray P816i-a w/ 5.53 firmware
iLO Firmware 2.42

**Comment by ariael** [comment]
Yes... This module is soooo much buggy, than i had to write my own module - completely rewrite into RedFish code and bypass smart array module....

Owner of this in real don't solve reported problem. This is shame for HP, i have to say.
I reported lots of problem, create incident, try direct way inside HP - but developers is separate part of HP and don't communicate with others part of HP. This is very bad situation for EVERY customer, who use powershell modules from production.

**Comment by hp-powershell** [comment]
Hi ,

Sorry for the inconvenience caused . We understand the hurdles you are facing here . 

in iLO 5 the creation of volumes does need reboot for them to take effect by behavior of iLO , this is being eliminated in iLO 6 which doesn't require reboot for creation to take effect . 

We have an upcoming release for SA cmdlets planned , if the gui\other command line tools are letting the creation of logics but cmdlets are not allowing same kindly provide us the execution steps and exception faced in an issue , we shall have it fixed.

Thanks for your patience . 

Thanks & Regards,
Powershell Team

**Comment by hp-powershell** [comment]
Hi ,

Kindly verify the issue with the latest released version of SA cmdlets which is HPESACmdlets 2.0 . If issue is still seen kindly reopen the ticket . 

thanks & Regards,
Powershell Team
