### ISSUE TITLE
Remove-HPESALogicalDrive not deleting volume

### ISSUE THREAD

**Issue by dbarstad** [HewlettPackard/PowerShell-ProLiant-SDK#71]
Remove-HPESALogicalDrive -Connection $SAConnection -ControllerLocation $SlotNumber -VolumeUniqueIdentifier $RemoveLogicalDrive 

Command returns successful, but on reboot the volume persists and OS starts to boot.

  HPEiLOCmdlets  : 3.1.0.1
  HPESmartArrayCmdlets : 1.0.0.2
  SmartArray P816i-a w/ 5.53 firmware
  iLO Firmware 2.42

**Comment by hp-powershell** [comment]
Hi,

We could successfully delete the logical drive using hpesmartarraycmdlets 1.0.0.2 . We are unable to reproduce .

Kindly recheck .

Thanks & Regards,
Powershell Team
