### ISSUE TITLE
No mechanism to generate additional arrays in provisioning

### ISSUE THREAD

**Issue by dbarstad** [HewlettPackard/PowerShell-ProLiant-SDK#72]
Trying to build ~100 servers in a Hadoop cluster with identical HW configs via scripting/automation.

HPESmartArrayCmdlets allow for creation of the base OS logical volume, but creating subsequent array/logicaldrives per the HPE Proliant Gen10 best practices for Hadoop, there is no method to create subsequent arrays/logical volumes via PowerShell CmdLets.

HP SSA provides a 'create array with R0 volume (from next drive)', but no option to create same configurations in HPESmartArrayCmdlets, even if done 'manually'.

  HPEiLOCmdlets  : 3.1.0.1
  HPESmartArrayCmdlets : 1.0.0.2
  SmartArray P816i-a w/ 5.53 firmware
  iLO Firmware 2.42

**Comment by hp-powershell** [comment]
Hi,

If the physical drive location is same , then by the iLO behavior the previous logical creation will get overridden with new. This is iLO behavior.

Hope this is what being asked here . 

if not kindly raise an issue with the cmdlets used and possible errors \obstacles faced .

Thanks & Regards,
Powershell Team
