### ISSUE TITLE
Ignoring or Disabling SNMPv1 via Script

### ISSUE THREAD

**Issue by goldenjc97** [HewlettPackard/PowerShell-ProLiant-SDK#73]
Can someone where how to disable and/or Ignore in security dashboard SNMPv1? Seems I can Ignore everything in Security Dashboard via HPEILO powershell commands, except this one.

**Comment by goldenjc97** [comment]
bump

**Comment by oliverwolfat** [comment]
This should do the trick.

```
# Disable SNMPv1 Alerts and Requests
Set-HPEiLOSNMPAlertSetting -Connection $iLO_Connection -SNMPv1Trap Disabled -SNMPv1Enabled Disabled
```

**Comment by goldenjc97** [comment]
Thanks Oliver! Will give that a try!
