### ISSUE TITLE
Set-HPEiLOSNMPSetting -SNMPConnectedVia does nothing

### ISSUE THREAD

**Issue by joshuaallenshaw** [HewlettPackard/PowerShell-ProLiant-SDK#75]
Assuming `$con` is the return from a successful `Connect-HPEiLO`, the following command fails to produce the desired result.
`$rtn = Set-HPEiLOSNMPSetting -Connection $con -SNMPConnectedVia AgentlessManagement -ReadCommunity1 public`

The result contained in `$rtn.StatusInfo.Message` is, "General System Read Community cannot be changed in SNMP PassThru Mode."
That error is plainly a problem, given that I the command that generated it is setting SNMP to "AgentlessManagment".

Running the command in debug reveals the following detail.
```
VERBOSE: [Set-HPEiLOSNMPSetting][10.6.241.242][RIBCL]: RIBCL command: <RIBCL VERSION="2.30">
  <LOGIN USER_LOGIN="administrator" PASSWORD="****">
    <RIB_INFO MODE="write">
      <MOD_SNMP_IM_SETTINGS>
        <SNMP_ADDRESS_1_ROCOMMUNITY VALUE="public" />
      </MOD_SNMP_IM_SETTINGS>
    </RIB_INFO>
  </LOGIN>
</RIBCL>
VERBOSE: [Set-HPEiLOSNMPSetting][10.6.241.242][RIBCL]: Getting web response.
```
Note that "<SNMP_PASSTHROUGH_STATUS VALUE="N" />" is not present in the RIBCL command.

I can see no evidence that the 'SNMPConnectedVia' parameter does anything.

**Comment by hp-powershell** [comment]
Hi ,

Kindly check with latest versions of ilO FWs and HPEiLOCmdlets ,

We couldnt reproduce the issue at our end .

Thanks & Regards,
Powershell Team
