### ISSUE TITLE
Set-HPEiLODirectorySetting doesn't work as expected

### ISSUE THREAD

**Issue by andreyyukhimchak** [HewlettPackard/PowerShell-ProLiant-SDK#76]
I tried to configure AD authentication for Gen10 servers with powershell module with something like this:
Set-HPEiLODirectorySetting -Connection $conn -DirectoryServerAddress '192.168.1.15' -DirectoryServerPort '3269'

Unfortunately for unknown reasons it's fill the **Directory Server Address** field with the next record **192.168.1.15:3269** (I see such value in iLO web interface) and authentication doesn't work.
At the same time when I read this value with Get-HPEiLODirectorySetting it shows DirectoryServerAddress as **192.168.1.15** without **:3269** suffix.

It was tested with version HPEiLOCmdlets 3.2.0.0 and 2.1 against few DL360 Gen10 servers and DX360 Gen10

**Comment by hp-powershell** [comment]
Hi ,

Server address and port when they are valid , it works fine in our environment with hpeilocmlets 3.2 which is the recent released version .

Kindly use the valid input and try again . 

thanks & regards,
Powershell Team
