### ISSUE TITLE
Disable IpV6

### ISSUE THREAD

**Issue by davidwallis** [HewlettPackard/PowerShell-ProLiant-SDK#77]
is there a command I can use with the redfish or ilo module / cmdlet that will allow disabling of ipv6 on the ilo mgmt processor (gen 10)

Thanks

David

**Comment by hp-powershell** [comment]
Hi ,

We have a cmdlet Set-HPEiLOIPv6NetworkSetting which lets changes in ipv6 configurations . Kindly check on the same .

Thanks & Regards,
Powershell Team
