### ISSUE TITLE
Request about Save-HPEiLOAHSLog

### ISSUE THREAD

**Issue by swahpy** [HewlettPackard/PowerShell-ProLiant-SDK#78]
Hi, 
I have many HPE machines to manage and I want to write a script to monitor the server status using HPEiLOCmdlets. At the point when I planned to download the AHS logs, I noticed that this function only support iLO5 and my tool just returned Error status. So here my questions are,
1. Do we have any plans to let this function support iLO4?
2. If not for the first question, do we have other ways to download AHS logs automatically via HPEiLOCmdlets.

Thank you very much and looking forward to your reply.

PS: We have thousands of machines, so it's nearly not possible to upgrade iLO4 to iLO5 for them.

**Comment by hp-powershell** [comment]
Hi ,

On investigating the URLs we see that from server we don't receive data currently for the current format of URL for ilo4 and ilo3 servers . 
https://{iLO4_IP}/ahsdata/HPE_SGH849SCKG_20230112.ahs?from=2022-11-10&to=2023-01-10

We will check again with iLO if they have an mechanism were we can collect the ahs log via cmdlet way . 

Thanks & Regards,
Powershell Team
