### ISSUE TITLE
Error when trying to manage certificates on iLO4 with HPEiLOCmdlets v. 2.0.0.1

### ISSUE THREAD

**Issue by e1pex** [HewlettPackard/PowerShell-ProLiant-SDK#8]
Start-HPEiLOCertificateSigningRequest, Get-HPEiLOCertificateSigningRequest  and Get-HPEiLOSSLCertificateInfo all fails with ERROR status on Proliant Gen8 and Gen9 Servers using the iLO 2.0.0.1 cmdlets. 

The HPE.iLO.Response.StatusInfo contains the following info
                    Category                 Message                         AffectedAttribute
                       --------                 -------                             -----------------
FeatureSupportability                 Feature not supported.   {}

The same code works on Gen10 servers and the corresponding cmdlets in the 1.5.0.0 codebase works on the Gen8 and Gen9 servers I've tried.

According to the [Scripting Tools for Windows PowerShell User Guide](https://support.hpe.com/hpsc/doc/public/display?docId=emr_na-a00051775en_us&docLocale=en_US) it should be supported.

I've also posted this issue in the HPE Community 
https://community.hpe.com/t5/Server-Management-Remote-Server/Error-when-trying-to-manage-certificates-on-iLO4-with/td-p/7017998

**Comment by CermakPOI** [comment]
I have this same issue with :
FirmwareDate    : Apr 28 2021
FirmwareVersion : 2,78
ManagerType     : iLO 4

and

Version    Name
-------    ----
3.1.0.1    HPEiLOCmdlets
