### ISSUE TITLE
no result: Enable-HPEiLOSecurityDashboardSetting -Connection $c -IgnoreDefaultSSLInUse

### ISSUE THREAD

**Issue by supersjimmie** [HewlettPackard/PowerShell-ProLiant-SDK#80]
I can do ```Disable-HPEiLOSecurityDashboardSetting -Connection $c -IgnoreDefaultSSLInUse``` and that turns off the toggle in the GUI.
However, when I do ```Enable-HPEiLOSecurityDashboardSetting -Connection $c -IgnoreDefaultSSLInUse``` the same toggle is not turned on.

**Comment by hp-powershell** [comment]
Hi ,

We are not able to reproduce this issue on the server at our end and we could toggle the settings .
we used the released version of HPEiLOCmdlets which is 3.2 for checking this 

Thanks & Regards,
POWERSHELL Team
