### ISSUE TITLE
enable/disable-HPEiLOSecurityDashboardSetting in HPEiLOCmdlets 4.0.0.0 missing SNMPv1

### ISSUE THREAD

**Issue by klaspihl** [HewlettPackard/PowerShell-ProLiant-SDK#86]
_Originally posted by @hp-powershell in https://github.com/HewlettPackard/PowerShell-ProLiant-SDK/issues/85#issuecomment-1416649575_

Your suggested solution **disables the SNMPv1** deamon in “Management – SNMP Settings” 

 SNMP v1/v2 is **needed for the monitoring** of server health. The issue is that the “Security Dashboard” is red complaining that “Overall Security Status : Risk” because SNMPv1 is enabled.  

The issue is **how to ignore SNMPv1 security parameter** like the other parameters in the security dashboard.

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us  .
Kindly test on the HPEiLOCmdlets 4.3 
we have enhanced the cmdlets Get & Set SNMPAlertSetting for SNMPv1 Trap Status
Kindly check on if this matches your requirement here  
Here not please reopen this issue . 

Thanks & Regards,
Powershell Team
