### ISSUE TITLE
Connecting to HPE Edgeline e920 Gen10plus doesn't work

### ISSUE THREAD

**Issue by SuperDonkey2000** [HewlettPackard/PowerShell-ProLiant-SDK#87]
Hi Team,

I'm referencing another "missing eisa ID" issue.
I'll try to connect to an/several Edgeline e920 server(s) - SKU P40891-B21
So can you please add, if possible, the corresponding "EISA ID" to your cmdlet?
I'm using HPEBIOSCmdlets 3.0.0.0

<EISA_Data ServerFamily="Edgeline" 
ServerModel="e920" 
ServerGeneration="Gen10Plus" 
ROM_Family="H10" 
ID="0E110887"/>

Hopefully my infos are correct. They're derived from an DL380 connection info.

Thanks & BR
Manuel

##########

Hi ,

Thanks for writing to us . 
We see that this server is not enabled in our HPEiLOCmdlets .

Kindly provide the below information for us to add it in our eisa ID mapper since these are moonshot servers the flow of the execution is through eisa id .

<EISA_Data ServerFamily="ProLiant" 
ServerModel="30" 
ServerGeneration="Gen10Plus" 
ROM_Family="U61" 
ID="0E110879"/>

Thanks & Regards,
Powershell Team

_Originally posted by @hp-powershell in https://github.com/HewlettPackard/PowerShell-ProLiant-SDK/issues/84#issuecomment-1407957542_

**Comment by hp-powershell** [comment]
Hi 

Kindly verify with the latest version of HPEiLOCmdlets . 
We see that the EisaID is already part of our codebase . 

Thanks & Regards,
Powershell Team
