### ISSUE TITLE
HPEiLOCmdlets - Get-HPEiLOLicense with iLO4. Works OK in v3.3.0.0 but errors in v4.0.0.0

### ISSUE THREAD

**Issue by mc1903** [HewlettPackard/PowerShell-ProLiant-SDK#90]
Just checking the support status with iLO4 and HPEiLOCmdlets v4.0.0.0?

I have been using `Get-HPEiLOLicense` to check the installed keys on iLO4's and it has worked with HPEiLOCmdlets v3.3.0.0.

Recently I have upgraded to v4.0.0.0 and the same operation now errors with "_Feature not supported on iLO3 and iLO4._"

I can still change license keys on iLO4's with  v4.0.0.0's `Set-HPEiLOLicense`, so it feels odd that I cannot check an installed key.

Is v4.0.0.0 deprecating iLO4 support? Is there a workaround/etc?

Thanks
M

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us 
we have fixed it with HPEiLOCmdlets 4.2 which is to be released in couple of days . 

Thanks & Regards,
Powershell Team

**Comment by hp-powershell** [comment]
Hi ,

The fix is released in our latest version HPEiLOCmdlets 4.2.0.0.

Thanks & Regards,
Powershell Team
