### ISSUE TITLE
HPEiLOCmdlets / Gen10 Plus issue with Get-HPEiloServerInfo

### ISSUE THREAD

**Issue by DAVIDMARTINEZROBLES** [HewlettPackard/PowerShell-ProLiant-SDK#91]
With differents version of ILOCMDLets and differents ilo version in Gen10 Plus show errors with command Get-HPEiloServerInfo

![image](https://github.com/HewlettPackard/PowerShell-ProLiant-SDK/assets/35568777/608f36d8-344a-4c97-a8a0-537fa645bdd8)

PSVersion 5.1.19041.2673

**Comment by hp-powershell** [comment]
Hi 

Can you provide us the difference in response object received . 
we are unable to reproduce .

Kindly also mention the iLO FW and generation information with cmdlet information . 

Thanks & Regards,
Powershell Team
