### ISSUE TITLE
Not able to disable SNMPv1

### ISSUE THREAD

**Issue by kesch095** [HewlettPackard/PowerShell-ProLiant-SDK#92]
Good day, 

I am not able to disable SNMPv1 using the HPE iLO Cmdlets v4.2.0. 

![image](https://github.com/HewlettPackard/PowerShell-ProLiant-SDK/assets/25568076/f3e2e3b2-0f42-414c-a20a-b36f844b1afe)

If disabled using the web gui it works fine. Enabling it with the same cmdlets also works fine.
We are using Synergy 480 Gen10 Nodes with iLO5 using SSP 2023.08.02

**Comment by hp-powershell** [comment]
Hi ,

Thanks for writing to us . 
Kindly check on the HPEiLOCmdlets 4.3 
we have enhanced the cmdlets Get & Set SNMPAlertSetting for SNMPv1 Trap Status

Kindly check on if this resolves your issue . If not please reopen this issue with the result . 

Thanks & Regards,
Powershell Team
